### ISSUE TITLE
`stdLambda` #performance

### ISSUE THREAD

**Issue by ws-garcia** [sancarn/stdVBA#51]
I have been playing with `stdLambda` and a doubt is gnawing my head. Why is the evaluation of a function like `sin(x)` **so slow compared to numeric evaluation** in this class module, given the fact it is a single operation?

**Comment by sancarn** [comment]
It's difficult to say for sure, it could be due to a number of reasons. Happy for help looking into exactly why. The relevant parts of the code are as follows:

1. [Function symbol](https://github.com/sancarn/stdVBA/blob/master/src/stdLambda.cls#L1008-L1013)
2. [Getting args off the stack](https://github.com/sancarn/stdVBA/blob/master/src/stdLambda.cls#L1094-L1113)
3. [Function evaluation](https://github.com/sancarn/stdVBA/blob/master/src/stdLambda.cls#L1185-L1364)

Some whatchouts: 

* Could be due to how much mem copying is going on, to prepare arguments etc.
* If you've added any overrides in `oFuncExt` that'd be why, as there is a check that `sin` is overwritten in the dictionary:

----

```
If TypeName(Me.oFunctExt) = "Dictionary" Then
        If Me.oFunctExt.exists(sFuncName) Then
            Dim vInjectedVar As Variant
            Call CopyVariant(vInjectedVar, oFunctExt(sFuncName))
            If TypeOf vInjectedVar Is stdICallable Then
                Call CopyVariant(evaluateFunc, Me.oFunctExt(sFuncName).RunEx(args))
            Else
                Call CopyVariant(evaluateFunc, vInjectedVar)
            End If
            Exit Function
        End If
    End If
```

**Comment by sancarn** [comment]
I've included this on the stdLambda performance megathread here:
https://github.com/sancarn/stdVBA/issues/49#issuecomment-1013042501

Please use this issue in future.
