### ISSUE TITLE
Application.Run() Alternative

### ISSUE THREAD

**Issue by ls-2037** [sancarn/stdVBA#64]
I noticed in the stdCallback code there are comments indicating that an alternative to Application.Run() might exist. Is this possible? Not all VBA host applications provide an Application.Run() method, and it can be very limiting to what you can do and which libraries/code you can use.

**Comment by sancarn** [comment]
Added, there are some nuances to using pointers though.

https://github.com/sancarn/stdVBA/blob/master/tests/stdCallbackTests.bas#L50-L86 gives a good idea of what you need to be careful of. You can either supply the argument types or they can be predicted but they can't be wrong. Same with the return type. Similarly if variables are declared byref (or not declared at all) then you need to pass pointers in instead of the variable itself...

Ultimately, calling by pointer becomes very tricky. Hope it makes sense, let me know if it works for you in your other vba environments.
